name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          cd fcj-workshop-huynhnguyenthanhtoan-main
          git submodule update --init --recursive

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.134.3"
          extended: true

      - run: cd fcj-workshop-huynhnguyenthanhtoan-main && hugo

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./fcj-workshop-huynhnguyenthanhtoan-main/public
